---
title: 'OpenBudget: A Shiny app for transparent finances in local government in North
  Macedonia'
authors: ['teo']
date: '2021-05-21'
slug: openbudget-a-shiny-app-for-transparent-finances-in-local-government-in-north-macedonia
categories:
  - R
  - Shiny
  - Open data
tags:
  - Metamorfosis Foundation
  - Hackathon
  - Finances
---

This week we were excited to take part in (and [win](https://metamorphosis.org.mk/aktivnosti_arhiva/odrzhan-hakaton-za-otvoreni-podatoci/)!) an Open Data Hackathon organized by the [Metamorfosis Foundation](https://metamorphosis.org.mk/en/), a prominent NGO in North Macedonia whose mission and vision are to "... strengthen the awareness and capacity of citizens and civil society ...". The whole experience was very interesting, from the consultations with the organizers and advisers, to the presentations and the projects of the other participants. We were overall very proud to further contribute to the discussions about open data in North Macedonia. This is a topic that we have been practicing and advocating for a long time, and we are glad that such initiatives are (finally) getting continous funding for development and implementation.

The hackathon competition was open for projects that will deliver a web application to visualize already available open data, or help with opening of datasets, making them closer to the public and easier to use. Discindo’s plan was to focus on some aspect of the financial functioning of local governments, because transparent financial practices, those that allow constituents to access, investigate, and understand how their tax money is being spent, are critical for building and maintaining citizens’ trust. Tools that facilitate such transparent local government budgets also seemed very fitting with the goals of the Metamorphosis Open Data initiatives. We therefore proposed to develop a web application that will enable municipalities to summarize, visualize, and deposit their yearly budgets of income or expenses into an open database accessible to everyone. 
Our solution addressed both relevant sides: Local governments benefit by having access to a tool for easy and intuitive communication of their finances to the public. Constituents benefit by being able to query, monitor, and compare local government budgets across years and municipalities.

Our demo application can be accessed here: https://discindo.shinyapps.io/OpenBudgetNMK/. Even at this early stage, the app has important functionality: to upload, join with metadata, aggregate, and visualize a yearly budget. Without such a tool, even with the best intentions, it is hard to communicate the details of the budget to the public, as the software used to generate the files outputs the data with numeric codes that have no meaning to the non-expert. We will complete development of the application this summer in anticipation of some substantive usage soon, as Metamorphosis continues their efforts to support the implementation of open and transparent data practices.
