project:
  type: website

website:
  title: "Discindo"
  site-url: https://discindo.org
  description: "Data science and data engineering solutions with R and Shiny in the cloud."
  google-analytics: 'GTM-T3SN4G9'
  cookie-consent: true
  navbar:
    right:
      - projects.qmd
      - series.qmd
      - about.qmd
      - icon: house
        href: https://discindodata.com
      - icon: github
        href: https://github.com/discindo
      - icon: cup
        href: https://ko-fi.com/discindo
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


